
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Alertas
{

    public Alertas()
    {

        this.AlertasVecinxs = new HashSet<AlertasVecinxs>();

    }


    public int idAlerta { get; set; }

    public string tipo { get; set; }

    public int codigo { get; set; }

    public bool android { get; set; }



    public virtual ICollection<AlertasVecinxs> AlertasVecinxs { get; set; }

}

}
