
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AlertasVecinxs
{

    public int idAlertaVecinx { get; set; }

    public int alertaId { get; set; }

    public int vecinxId { get; set; }



    public virtual Alertas Alertas { get; set; }

    public virtual Vecinos Vecinos { get; set; }

}

}
