
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CompraProducto
{

    public int idCompraProducto { get; set; }

    public int compraId { get; set; }

    public int productoId { get; set; }

    public int cantidad { get; set; }

    public Nullable<int> costoId { get; set; }

    public Nullable<int> precioId { get; set; }



    public virtual Compras Compras { get; set; }

    public virtual Costos Costos { get; set; }

    public virtual Precios Precios { get; set; }

    public virtual Productos Productos { get; set; }

}

}
