
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Locales
{

    public Locales()
    {

        this.Compras = new HashSet<Compras>();

        this.ProductosLocales = new HashSet<ProductosLocales>();

        this.Vecinos = new HashSet<Vecinos>();

    }


    public int idLocal { get; set; }

    public string nombre { get; set; }

    public string direccion { get; set; }

    public string barrio { get; set; }

    public string horario { get; set; }

    public int comuna { get; set; }

    public int circuitoId { get; set; }

    public bool activo { get; set; }



    public virtual Circuitos Circuitos { get; set; }

    public virtual ICollection<Compras> Compras { get; set; }

    public virtual ICollection<ProductosLocales> ProductosLocales { get; set; }

    public virtual ICollection<Vecinos> Vecinos { get; set; }

}

}
