
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Noticias
{

    public int idNoticia { get; set; }

    public string titulo { get; set; }

    public string copete { get; set; }

    public string link { get; set; }

    public string imagen { get; set; }

    public string categoria { get; set; }

    public string tags { get; set; }

    public string autor { get; set; }

    public Nullable<System.DateTime> fecha { get; set; }

}

}
