
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Productos
{

    public Productos()
    {

        this.ComentariosProducto = new HashSet<ComentariosProducto>();

        this.CompraProducto = new HashSet<CompraProducto>();

        this.Costos = new HashSet<Costos>();

        this.Precios = new HashSet<Precios>();

        this.ProductosLocales = new HashSet<ProductosLocales>();

    }


    public int idProducto { get; set; }

    public string producto { get; set; }

    public string descripcion { get; set; }

    public string marca { get; set; }

    public string presentacion { get; set; }

    public string proveedor { get; set; }

    public string variedad { get; set; }

    public int stock { get; set; }

    public bool activo { get; set; }

    public Nullable<int> categoriaId { get; set; }



    public virtual Categorias Categorias { get; set; }

    public virtual ICollection<ComentariosProducto> ComentariosProducto { get; set; }

    public virtual ICollection<CompraProducto> CompraProducto { get; set; }

    public virtual ICollection<Costos> Costos { get; set; }

    public virtual ICollection<Precios> Precios { get; set; }

    public virtual ICollection<ProductosLocales> ProductosLocales { get; set; }

}

}
