
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Relevamientos
{

    public int idRelevamiento { get; set; }

    public string fruta { get; set; }

    public string tipo { get; set; }

    public int cantidad { get; set; }

    public decimal precio { get; set; }

    public string donde { get; set; }

    public System.DateTime fechaRelevado { get; set; }

    public System.DateTime fechaSincronizado { get; set; }

}

}
