
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Roles
{

    public Roles()
    {

        this.RolesVecinos = new HashSet<RolesVecinos>();

    }


    public int idRol { get; set; }

    public string nombre { get; set; }

    public int codigoRol { get; set; }



    public virtual ICollection<RolesVecinos> RolesVecinos { get; set; }

}

}
