
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Economia_Social_Y_Solidaria.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tandas
{

    public Tandas()
    {

        this.Compras = new HashSet<Compras>();

    }


    public int idTanda { get; set; }

    public System.DateTime fechaAbierto { get; set; }

    public Nullable<System.DateTime> fechaCerrado { get; set; }

    public Nullable<System.DateTime> fechaVenta { get; set; }

    public int circuitoId { get; set; }

    public int vecinoId { get; set; }



    public virtual Circuitos Circuitos { get; set; }

    public virtual ICollection<Compras> Compras { get; set; }

    public virtual Vecinos Vecinos { get; set; }

}

}
